apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: code-pipeline-009
  annotations:
    scenarios.ai.sap.com/description: "Tutorial to add custom code to SAP AI Core"
    scenarios.ai.sap.com/name: "Code (Tutorial)"
    executables.ai.sap.com/description: "Trains model on median house prices"
    executables.ai.sap.com/name: "House Price (Sklearn Example)"
    artifacts.ai.sap.com/textmodel.kind: "model"
    artifacts.ai.sap.com/textmodel.description: "artifact description"
  labels:
    scenarios.ai.sap.com/id: "house-price"
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
        - name: sap-ai-core-test-docker-registry-creds
        minReplicas: 0
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/sajjas/house-price:0.0.3
          ports:
            - containerPort: 9001
              protocol: TCP